In [2]:
import torch
from torch.autograd import Variable
x = Variable(torch.randn(3), requires_grad=True)
y = Variable(torch.randn(3), requires_grad=True)
z = Variable(torch.randn(3), requires_grad=True)
print(x)
print(y)
print(z)


tensor([ 2.5156, -0.3900, -0.2182], requires_grad=True)
tensor([ 0.1944,  0.6449, -0.8953], requires_grad=True)
tensor([-0.9199, -0.0459,  0.3010], requires_grad=True)


In [3]:
t = x + y
l = t.dot(z)
l.backward(retain_graph=True)

In [4]:
print(x.grad)
print(y.grad)
print(z)
print(z.grad)

tensor([-0.9199, -0.0459,  0.3010])
tensor([-0.9199, -0.0459,  0.3010])
tensor([-0.9199, -0.0459,  0.3010], requires_grad=True)
tensor([ 2.7101,  0.2549, -1.1135])


In [5]:
y = torch.randn(2, 2)
print(y)

tensor([[-0.4059,  0.5957],
        [-0.2747, -1.1919]])


chp3.1 begin


In [2]:
import torch
from time import time
a = torch.ones(1000)
b = torch.ones(1000)

start = time()
c = torch.zeros(1000)
for i in range(1000):
    c[i] = a[i] + b[i]
print(time() - start)

0.015305519104003906


In [3]:
a = torch.ones(3)
b = 10
print(a + b)

tensor([11., 11., 11.])
