In [18]:
import torch
import torch.nn as nn
import numpy
m = nn.ConvTranspose2d(16, 33, 3, stride=2)
m = nn.ConvTranspose2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
input = torch.randn(20, 16, 50, 100)
output = m(input)

In [126]:
upsample = nn.ConvTranspose2d(96, 48, [1, 10], [1, 5], [0, 3], [0, 1], bias=False)
input1 = torch.randn(1, 96, 1, 5968)
output1 = upsample(input1)
print(output1.shape)

torch.Size([1, 48, 1, 29840])


In [160]:
upsample = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=[1, 10], stride=[1, 5], padding=[0, 0], 
                              output_padding=[0, 1], bias=False)
input1 = torch.randn(1, 1, 1, 4)
output1 = upsample(input1)
print(output1.shape)

torch.Size([1, 1, 1, 26])


In [163]:
output2 = output1.detach().numpy()
print(output2[0, 0, 0, 24])

0.01530235


In [164]:
print(input1)
print(output1)
print(output2[0,0,0,0])

tensor([[[[-1.2792,  0.4231,  0.9616,  0.3945]]]])
tensor([[[[ 0.1298, -0.2798,  0.3539,  0.1011,  0.3658,  0.2608, -0.1791,
           -0.1727, -0.1222, -0.1706, -0.1980,  0.3002, -0.2476, -0.0466,
           -0.2586, -0.2683,  0.2905, -0.0673,  0.0355, -0.0755, -0.0937,
            0.0838,  0.0172,  0.0274,  0.0153,  0.0000]]]],
       grad_fn=<SlowConvTranspose2DBackward>)
0.12978078


In [165]:
print(upsample.weight)

Parameter containing:
tensor([[[[-0.1015,  0.2187, -0.2766, -0.0790, -0.2860, -0.2374,  0.2124,
            0.0435,  0.0694,  0.0388]]]], requires_grad=True)


In [166]:
print(upsample.bias)

None


In [167]:
weight=upsample.weight.detach().numpy()
input1_np=input1.numpy()

In [168]:
print(upsample.weight.shape)
print(weight[0,0,0,3])
print(input1_np[0,0,0,0])
out0 = weight[0, 0, 0, 0]*input1_np[0,0,0,0]
print(out0)

torch.Size([1, 1, 1, 10])
-0.0790384
-1.2792253
0.12978078


# Deconv2d
验证在h和w上，卷积weight的顺序是逆序

In [174]:
upsample2 = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=[3, 3], stride=[1, 1], padding=[0, 0], 
                              output_padding=[0, 0], bias=False)
input2 = torch.randn(1, 1, 4, 4)
output2 = upsample2(input2)
print(output2.shape)

torch.Size([1, 1, 6, 6])


In [176]:
print(upsample2.weight)
print(upsample2.weight.shape)

Parameter containing:
tensor([[[[-0.2689, -0.2103,  0.1406],
          [-0.0350,  0.3073,  0.2371],
          [ 0.1391,  0.2286, -0.2492]]]], requires_grad=True)
torch.Size([1, 1, 3, 3])


In [185]:
weight2=upsample2.weight.detach().numpy()
input2_np=input2.numpy()

In [186]:
print(input2)

tensor([[[[ 0.2258,  0.4327,  2.5477,  0.5874],
          [-0.8957,  0.4242, -1.3100, -0.2536],
          [-1.2626, -0.6155, -1.1006,  0.0755],
          [-0.4319, -1.1705, -0.6834, -0.2719]]]])


In [187]:
print(output2)

tensor([[[[-0.0607, -0.1638, -0.7443, -0.6329,  0.2348,  0.0826],
          [ 0.2329,  0.1286,  0.2343,  1.2684,  0.6538,  0.1036],
          [ 0.4023,  0.2527,  0.6087,  0.3876, -1.0599, -0.1959],
          [ 0.0358, -0.1066,  0.0571, -0.8751, -0.0082,  0.0429],
          [-0.1605, -0.4659, -0.4174, -0.5657,  0.0460, -0.0833],
          [-0.0601, -0.2616, -0.2550,  0.0977,  0.1082,  0.0678]]]],
       grad_fn=<SlowConvTranspose2DBackward>)


In [189]:
print(weight2[0,0,0,0])
out2_0=weight2[0,0,0,0] * input2_np[0,0,0,0]
print(out2_0)

-0.26887915
-0.06071747
