In [6]:
import tensorflow as tf

In [7]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[4, 5], [7, 8]])
C = tf.matmul(A, B)
print(C)

tf.Tensor(
[[18 21]
 [40 47]], shape=(2, 2), dtype=int32)


# 1.Tensor

In [8]:
random_float = tf.random.uniform(shape=())
print(random_float)

tf.Tensor(0.39043653, shape=(), dtype=float32)


In [9]:
zero_vector = tf.zeros(shape=(2))
print(zero_vector)

tf.Tensor([0. 0.], shape=(2,), dtype=float32)


In [10]:
x = tf.Variable(initial_value = 3.0)
with tf.GradientTape() as tape:
    y = tf.square(x)
y_grad = tape.gradient(y, x)
print([y, y_grad])

[<tf.Tensor: shape=(), dtype=float32, numpy=9.0>, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>]


In [16]:
X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.], [2.]])
w = tf.Variable(initial_value = [[1.], [2.]])
b = tf.Variable(initial_value = 1.)
with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(X, w) + b - y))
w_grad, b_grad = tape.gradient(L, [w, b])
print(L, w_grad, b_grad)

tf.Tensor(125.0, shape=(), dtype=float32) tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32) tf.Tensor(30.0, shape=(), dtype=float32)


# 2. Gradient: y = tf.square() below with 

In [14]:
import tensorflow as tf

x = tf.Variable(initial_value = 4.0)
with tf.GradientTape() as tape:
    y = tf.square(x)
    y_grad = tape.gradient(y, x)
print([y, y_grad])

[<tf.Tensor: shape=(), dtype=float32, numpy=16.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.0>]


# 3. Numpy Linear

In [25]:
import numpy as np

# y = a * x + b  
x_raw = np.array([2013, 2014, 2015, 2016, 2017], dtype = np.float32)
y_raw = np.array([12000, 14000, 15000, 16500, 17500], dtype = np.float32)

x = (x_raw - x_raw.min()) / (x_raw.max() - x_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())

print(x)
print(y)

# mina,bL(a, b) = (ax + b  - y)^2
# grad_a = 2 * (ax + b - y) * x = 2 * (y_pred - y).dot(x)
# grad_b = 2 * (a * x + b - y) * 1 = 2 * (y_pred - y)
a, b = 0, 0
num_epoch = 10000
learning_rate = 1e-3
for e in range(num_epoch):
    y_pred = a * x + b
    grad_a, grad_b = 2 * (y_pred - y).dot(x), 2 * (y_pred - y).sum()
    a, b = a - learning_rate * grad_a, b - learning_rate * grad_b
print(a, b)

[0.   0.25 0.5  0.75 1.  ]
[0.         0.36363637 0.54545456 0.8181818  1.        ]
0.9817775010019512 0.05456800667941586


In [26]:
import numpy as np
x = np.array([1, 2, 3, 4], dtype = np.float32)
y = np.array([1, 2, 3, 4], dtype = np.float32)
z = np.dot(x, y)
print(z)

30.0


In [27]:
x = np.array([1, 2, 3, 4], dtype = np.float32)
print(x.sum())

10.0


In [31]:
lists = ["rudy", "ruby", "caocao", "liubei", "sunquan"]
print(lists)
lists[2] = "aman"
print(lists)
print(lists[-1])
del (lists[1])
print(lists)

['rudy', 'ruby', 'caocao', 'liubei', 'sunquan']
['rudy', 'ruby', 'aman', 'liubei', 'sunquan']
sunquan
['rudy', 'aman', 'liubei', 'sunquan']


# 4. tensorflow linear

In [40]:
# X not defined 
import tensorflow as tf

x_raw = np.array([2013, 2014, 2015, 2016, 2017], dtype = np.float32)
y_raw = np.array([12000, 14000, 15000, 16500, 17500], dtype = np.float32)

x = (x_raw - x_raw.min()) / (x_raw.max() - x_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())

x = tf.constant(x)
y = tf.constant(y)

a = tf.Variable(initial_value = 0.)
b = tf.Variable(initial_value = 0.)
variables = [a, b]

num_epoch = 10000
optimizer = tf.keras.optimizers.SGD(learning_rate = 1e-3)
for e in range(num_epoch):
    with tf.GradientTape() as tape:
        y_pred = a * x + b
        loss = tf.reduce_sum(tf.square(y_pred - y))
        
    grads = tape.gradient(loss, variables)
    optimizer.apply_gradients(grads_and_vars = zip(grads, variables))


print(a, b)


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.9817748> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0545703>


In [53]:
y = ("x", "y", "z", "a", "b")
x = [1, 2, 3, 4, 5]
c = list(y)
c[2] = "zz"
c.extend(x)
print(c)
for i in x:
    print(len(x), i)

['x', 'y', 'zz', 'a', 'b', 1, 2, 3, 4, 5]
5 1
5 2
5 3
5 4
5 5
